spring.application.name=auth-service
server.port=8081

# --- W PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=admin

# --- Pool HikariCP P ---
spring.datasource.hikari.pool-name=auth-pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=5000

# --- JPA / Hibernate ---*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false 
